version: '3.3'

services:
  postgres:
    image: postgres:11.5-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=customer-review-postgres
  agent:
    container_name: customer-review-consul
    ports:
      - '8500:8500'
      - '8600:8600/udp'
      - '-expect=1'
    environment:
      - true
      - true
      - server-1
      - true
    volumes:
      - 'true'
    image: agent
  keycloak:
    image: jboss/keycloak:12.0.4
    ports:
      - 8888:8080
    environment:
      - KEYCLOAK_USER=keycloak
      - KEYCLOAK_PASSWORD=keycloak
      - DB_VENDOR=h2
      - JAVA_OPTS=-Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/tmp/stratospheric-realm.json
    volumes:
      - ./init/stratospheric-realm.json:/tmp/stratospheric-realm.json

#version: '3.8'
#services:
#  database:
#    image: postgres:11.5-alpine
#    environment:
#      - POSTGRES_USER=test
#      - POSTGRES_PASSWORD=test
#    ports:
#      - 5432:5432
#  keycloak:
#    image: jboss/keycloak:11.0.0
#    environment:
#      - KEYCLOAK_USER=keycloak
#      - KEYCLOAK_PASSWORD=keycloak
#      - DB_VENDOR=h2
#      - JAVA_OPTS=-Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/tmp/keycloak-dump.json
#    volumes:
#      - type: bind
#        source: ./tmp/keycloak-dump.json
#        target: /tmp/keycloak-dump.json
#        read_only: true
#    ports:
#      - 8888:8080
#  sqs:
#    image: roribio16/alpine-sqs:latest
#    ports:
#      - 9324:9324
#      - 9325:9325